### ISSUE TITLE
SH4OSDAdjustment conflics with OSDAdjustments from OpenPLi

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#21]
SH4OSDAdjustment for spark conflicts with OSDAdjustments and adjusments you make are not working after reboot. I simply removed SH4OSDAdjustments from system plugins and it is ok then.

**Comment by lprot** [comment]
Is SH4OSDAjustments any better than original OSDAjustments?

**Comment by MastaG** [comment]
For now I've removed PLi's OSDPositionSetup plugin from SH4 so I can debug the SH4 version.
See: https://github.com/PLi-metas/meta-fulan/commit/30c547a5c5f1e7b93e005bcfd30ab821c86b6934

I'll look into it later when I have my spark receiver hooked up.

**Comment by lprot** [comment]
OSDPositionSetup is working ok. Why do we need SH4 version at all?

**Comment by MastaG** [comment]
Because the SH4 version is what gets installed with OE-Alliance as well.
See: https://github.com/oe-alliance/oe-alliance-plugins/tree/master/SH4OSDAdjustment
And: https://github.com/oe-alliance/oe-alliance-plugins/blob/3ae6c85f9ce4e7a7b3d563a86dbb77025168928d/Makefile.am#L282

So I'd rather look into why that one doesn't work because it should be made specifically for SH4 receivers.

**Comment by MastaG** [comment]
fixed now in openpli-enigma2-fulan, sh4 osd adjustment will now show up.
