### ISSUE TITLE
Gstreamer playing on spark goes stuttering

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#29]
The image I compiled has exteplayer + gstreamer.
exteplayer plays streams with hw acceleration and works ok.
But if I play the same streams in gstreamer it is stuttering - like hw acceleration is off.
I wonder if it's easy fixable.

**Comment by kueken** [comment]
Is a problem of the gst. No problem with the image.

**Comment by lprot** [comment]
On dm800hd it plays w/o stuttering.

**Comment by kueken** [comment]
The comparison with the Dream helps little here.
GST-Mediaframwork is somewhat problematic on some models.
That's why Taapat only used libeplayer and thus ffmpeg at sh4.
In the current image you have the choice between libeplayer (exteplayer) and gst.
The recommendation is clearly still ffmpeg based.
That was always the first choice for sh4. Also with other boxes this is always worth a try.
If there is something to do, it would be from gst.
What is feasible in connection with the image is already being done.
Please use the exteplayer3 via service app, then it runs quite carefree.
