### ISSUE TITLE
GCC 4.9

### ISSUE THREAD

**Issue by persianpros** [PLi-metas/pli-extras#30]
Hello friends :)

Would you please test https://github.com/PLi-metas/pli-extras#ebox build? (Example: ebox5000)

It uses https://github.com/PLi-metas/meta-ebox/blob/develop/conf/machine/include/ebox-oem.inc#L26 and gives me error on Ubuntu 18.04 LTS :(

Thanks in advance

**Comment by Hains** [comment]
I had compile error mpg123, but thanks to this:
https://github.com/voidlinux/void-packages/issues/4671
it does build now.
Image almost ready (ebox5000).
I'll make patch for mpg123 ebox.

**Comment by Hains** [comment]
And now  servicemp3.cpp :(. Two errors.
I'll see if i can fix it.

**Comment by persianpros** [comment]
:(
If the patch is global you can add it to pli-extras otherwise add it to meta-ebox please.

**Comment by MastaG** [comment]
Fulan uses gcc 4.9 as the sh4 architecture is ancient.
Check the bbappends in there for the recipes that fail.
They all have bbappends with some append_sh4 prefix.

**Comment by Hains** [comment]
I'll  make patch for mpg123 tomorrow.
Since it just include a header file it shouldn't break other boxes.
I'll add it pli-extras.

So for sh4 we're stuck to gcc 4..
Great.

**Comment by MastaG** [comment]
Yeah.
Sh4 = kernel 2.6.32, gcc 4.9 and glibc 2.23
Dm800 = kernel 2.6.18 and (e)glibc 2.19

For the dm800 I've been hacking up the kernel to allow it to build with recent compilers.

For sh4, anything above gcc 4.9 fails as the sh4 architecture isnt supported anymore.
But since there isnt any other receivers (or BSP layers) using sh4. It doesnt hurt the rest.

Both will work in OE sumo with some fiddling (as I also got it to work for pyro).

But when PLi decides to switch to systemd its game over for anything running an older kernel than 3.2.

**Comment by Hains** [comment]
luckily for me, ebox5000 is mipsel and kernel 3.12.4.:).

https://github.com/PLi-metas/meta-ebox/commit/0610eae8aa841ffc1147516185d750304db1e61d

No patches needed.
Image ready.

**Comment by persianpros** [comment]
Will the drivers now work? We should find a tester ...
